-- Modulo 1: Reclutamiento y seleccion de personal
-- Basado en las entidades del UML: VACANTE, REQUISITO_VACANTE, CANDIDATO,
-- POSTULACION, ENTREVISTA y la transicion hacia EMPLEADO.
-- Nota: el esquema de produccion usa nombres en plural (vacantes, candidatos,
-- postulaciones, entrevistas, empleados). El repositorio apunta a estas tablas.

create table if not exists public.departamentos (
  id_departamento bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text
);

create table if not exists public.cargos (
  id_cargo bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  id_departamento bigint references public.departamentos(id_departamento)
);

create table if not exists public.vacantes (
  id_vacante bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text not null,
  id_departamento bigint references public.departamentos(id_departamento),
  fecha_publicacion date not null default current_date,
  estado text not null default 'Abierta',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vacantes_estado_check check (estado in ('Abierta', 'En evaluacion', 'Cerrada'))
);

create table if not exists public.requisito_vacante (
  id_requisito bigint generated by default as identity primary key,
  id_vacante bigint not null references public.vacantes(id_vacante) on delete cascade,
  descripcion text not null,
  tipo text not null,
  created_at timestamptz not null default now(),
  constraint requisito_vacante_tipo_check check (tipo in ('Requisito', 'Responsabilidad'))
);

create table if not exists public.candidatos (
  id_candidato bigint generated by default as identity primary key,
  nombre text not null,
  apellido text,
  cedula text not null unique,
  correo text not null unique,
  telefono text not null,
  ubicacion text not null,
  fecha_nacimiento date,
  educacion text not null,
  experiencia_profesional text not null,
  estado text,
  resumen_profesional text,
  score_ia integer,
  experiencia_ia text,
  especializacion_ia text,
  recomendado_ia boolean,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.postulaciones (
  id_postulacion bigint generated by default as identity primary key,
  id_candidato bigint not null references public.candidatos(id_candidato) on delete cascade,
  id_vacante bigint not null references public.vacantes(id_vacante) on delete cascade,
  fecha_postulacion date not null default current_date,
  estado text not null default 'En evaluacion',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint postulaciones_estado_check check (
    estado in ('En evaluacion', 'Aprobado', 'Rechazado', 'Contratado')
  ),
  constraint postulaciones_candidato_vacante_unique unique (id_candidato, id_vacante)
);

create table if not exists public.entrevistas (
  id_entrevista bigint generated by default as identity primary key,
  id_postulacion bigint not null references public.postulaciones(id_postulacion) on delete cascade,
  fecha_entrevista date not null,
  entrevistador text not null,
  observaciones text not null,
  resultado text not null default 'Pendiente',
  created_at timestamptz not null default now(),
  constraint entrevistas_resultado_check check (
    resultado in ('Pendiente', 'Aprobado', 'Rechazado', 'Requiere segunda entrevista')
  )
);

create table if not exists public.empleados (
  id_empleado bigint generated by default as identity primary key,
  id_candidato bigint references public.candidatos(id_candidato),
  nombre text not null,
  apellido text not null,
  cedula text not null unique,
  fecha_nacimiento date,
  direccion text,
  telefono text,
  email text,
  fecha_ingreso date not null default current_date,
  fecha_salida date,
  estado text not null default 'Activo',
  id_cargo bigint references public.cargos(id_cargo),
  id_departamento bigint references public.departamentos(id_departamento),
  salario_inicial numeric(12, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Columnas de analisis de CV con IA (compatibilidad con esquemas pre-existentes).
alter table public.candidatos
  add column if not exists apellido text,
  add column if not exists score_ia integer,
  add column if not exists experiencia_ia text,
  add column if not exists especializacion_ia text,
  add column if not exists recomendado_ia boolean;

create index if not exists idx_vacantes_departamento on public.vacantes(id_departamento);
create index if not exists idx_requisito_vacante on public.requisito_vacante(id_vacante);
create index if not exists idx_postulaciones_candidato on public.postulaciones(id_candidato);
create index if not exists idx_postulaciones_vacante on public.postulaciones(id_vacante);
create index if not exists idx_postulaciones_estado on public.postulaciones(estado);
create index if not exists idx_entrevistas_postulacion on public.entrevistas(id_postulacion);
create index if not exists idx_empleados_candidato on public.empleados(id_candidato);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_vacantes_updated_at on public.vacantes;
create trigger set_vacantes_updated_at
before update on public.vacantes
for each row execute function public.set_updated_at();

drop trigger if exists set_candidatos_updated_at on public.candidatos;
create trigger set_candidatos_updated_at
before update on public.candidatos
for each row execute function public.set_updated_at();

drop trigger if exists set_postulaciones_updated_at on public.postulaciones;
create trigger set_postulaciones_updated_at
before update on public.postulaciones
for each row execute function public.set_updated_at();

drop trigger if exists set_empleados_updated_at on public.empleados;
create trigger set_empleados_updated_at
before update on public.empleados
for each row execute function public.set_updated_at();

alter table public.departamentos enable row level security;
alter table public.cargos enable row level security;
alter table public.vacantes enable row level security;
alter table public.requisito_vacante enable row level security;
alter table public.candidatos enable row level security;
alter table public.postulaciones enable row level security;
alter table public.entrevistas enable row level security;
alter table public.empleados enable row level security;

-- Politicas sugeridas para activar despues de definir autenticacion/roles.
-- create policy "rrhh_read_hiring" on public.vacantes for select using (...);
-- create policy "rrhh_write_hiring" on public.vacantes for all using (...) with check (...);
