-- Modulo 1: Reclutamiento y seleccion de personal
-- Basado en las entidades del UML: VACANTE, REQUISITO_VACANTE, CANDIDATO,
-- POSTULACION, ENTREVISTA y la transicion hacia EMPLEADO.

create table if not exists public.departamento (
  id_departamento bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text
);

create table if not exists public.cargo (
  id_cargo bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  id_departamento bigint references public.departamento(id_departamento)
);

create table if not exists public.vacante (
  id_vacante bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text not null,
  id_departamento bigint references public.departamento(id_departamento),
  fecha_publicacion date not null default current_date,
  estado text not null default 'Abierta',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vacante_estado_check check (estado in ('Abierta', 'En evaluacion', 'Cerrada'))
);

create table if not exists public.requisito_vacante (
  id_requisito bigint generated by default as identity primary key,
  id_vacante bigint not null references public.vacante(id_vacante) on delete cascade,
  descripcion text not null,
  tipo text not null,
  created_at timestamptz not null default now(),
  constraint requisito_vacante_tipo_check check (tipo in ('Requisito', 'Responsabilidad'))
);

create table if not exists public.candidato (
  id_candidato bigint generated by default as identity primary key,
  nombre text not null,
  apellido text not null,
  cedula text not null unique,
  email text not null unique,
  telefono text not null,
  direccion text not null,
  fecha_nacimiento date,
  nivel_academico text not null,
  experiencia_laboral text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.postulacion (
  id_postulacion bigint generated by default as identity primary key,
  id_candidato bigint not null references public.candidato(id_candidato) on delete cascade,
  id_vacante bigint not null references public.vacante(id_vacante) on delete cascade,
  fecha_postulacion date not null default current_date,
  estado text not null default 'En evaluacion',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint postulacion_estado_check check (
    estado in ('En evaluacion', 'Aprobado', 'Rechazado', 'Contratado')
  ),
  constraint postulacion_candidato_vacante_unique unique (id_candidato, id_vacante)
);

create table if not exists public.entrevista (
  id_entrevista bigint generated by default as identity primary key,
  id_postulacion bigint not null references public.postulacion(id_postulacion) on delete cascade,
  fecha_entrevista date not null,
  entrevistador text not null,
  observaciones text not null,
  resultado text not null default 'Pendiente',
  created_at timestamptz not null default now(),
  constraint entrevista_resultado_check check (
    resultado in ('Pendiente', 'Aprobado', 'Rechazado', 'Requiere segunda entrevista')
  )
);

create table if not exists public.empleado (
  id_empleado bigint generated by default as identity primary key,
  id_candidato bigint references public.candidato(id_candidato),
  nombre text not null,
  apellido text not null,
  cedula text not null unique,
  fecha_nacimiento date,
  direccion text,
  telefono text,
  email text,
  fecha_ingreso date not null default current_date,
  fecha_salida date,
  estado text not null default 'Activo',
  id_cargo bigint references public.cargo(id_cargo),
  id_departamento bigint references public.departamento(id_departamento),
  salario_inicial numeric(12, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_vacante_departamento on public.vacante(id_departamento);
create index if not exists idx_requisito_vacante on public.requisito_vacante(id_vacante);
create index if not exists idx_postulacion_candidato on public.postulacion(id_candidato);
create index if not exists idx_postulacion_vacante on public.postulacion(id_vacante);
create index if not exists idx_postulacion_estado on public.postulacion(estado);
create index if not exists idx_entrevista_postulacion on public.entrevista(id_postulacion);
create index if not exists idx_empleado_candidato on public.empleado(id_candidato);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_vacante_updated_at on public.vacante;
create trigger set_vacante_updated_at
before update on public.vacante
for each row execute function public.set_updated_at();

drop trigger if exists set_candidato_updated_at on public.candidato;
create trigger set_candidato_updated_at
before update on public.candidato
for each row execute function public.set_updated_at();

drop trigger if exists set_postulacion_updated_at on public.postulacion;
create trigger set_postulacion_updated_at
before update on public.postulacion
for each row execute function public.set_updated_at();

drop trigger if exists set_empleado_updated_at on public.empleado;
create trigger set_empleado_updated_at
before update on public.empleado
for each row execute function public.set_updated_at();

alter table public.departamento enable row level security;
alter table public.cargo enable row level security;
alter table public.vacante enable row level security;
alter table public.requisito_vacante enable row level security;
alter table public.candidato enable row level security;
alter table public.postulacion enable row level security;
alter table public.entrevista enable row level security;
alter table public.empleado enable row level security;

-- Politicas sugeridas para activar despues de definir autenticacion/roles.
-- create policy "rrhh_read_hiring" on public.vacante for select using (...);
-- create policy "rrhh_write_hiring" on public.vacante for all using (...) with check (...);
