-- ShiftAI - Modulo 5: Capacitacion y Desarrollo
-- Ejecutar en Supabase SQL Editor antes de usar TRAINING_STORAGE=supabase.

CREATE TABLE IF NOT EXISTS cursos_capacitacion (
  id_curso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT GENERATED ALWAYS AS ('CUR-' || LPAD(id_curso::TEXT, 3, '0')) STORED UNIQUE,
  nombre VARCHAR(160) NOT NULL,
  descripcion TEXT NOT NULL DEFAULT '',
  categoria VARCHAR(80) NOT NULL,
  departamento_objetivo VARCHAR(100) NOT NULL DEFAULT 'Todos los departamentos',
  proveedor VARCHAR(120) NOT NULL,
  duracion_horas INTEGER NOT NULL CHECK (duracion_horas BETWEEN 1 AND 2000),
  modalidad VARCHAR(20) NOT NULL CHECK (modalidad IN ('Virtual', 'Presencial', 'Híbrido')),
  cupo_maximo INTEGER NOT NULL CHECK (cupo_maximo BETWEEN 1 AND 10000),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS cursos_capacitacion_nombre_unique
  ON cursos_capacitacion (LOWER(nombre));

CREATE TABLE IF NOT EXISTS programas_capacitacion (
  id_programa BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT GENERATED ALWAYS AS ('PROG-' || LPAD(id_programa::TEXT, 3, '0')) STORED UNIQUE,
  nombre VARCHAR(160) NOT NULL,
  descripcion TEXT NOT NULL DEFAULT '',
  departamento_objetivo VARCHAR(100) NOT NULL DEFAULT 'Todos los departamentos',
  nivel VARCHAR(60) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS programas_capacitacion_nombre_unique
  ON programas_capacitacion (LOWER(nombre));

CREATE TABLE IF NOT EXISTS programa_cursos (
  id_programa BIGINT NOT NULL REFERENCES programas_capacitacion(id_programa) ON DELETE CASCADE,
  id_curso BIGINT NOT NULL REFERENCES cursos_capacitacion(id_curso) ON DELETE RESTRICT,
  orden INTEGER NOT NULL DEFAULT 1 CHECK (orden > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id_programa, id_curso)
);

CREATE TABLE IF NOT EXISTS capacitaciones_empleados (
  id_asignacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT GENERATED ALWAYS AS ('ASG-' || LPAD(id_asignacion::TEXT, 3, '0')) STORED UNIQUE,
  id_empleado BIGINT NOT NULL REFERENCES empleados(id_empleado) ON DELETE RESTRICT,
  id_curso BIGINT NOT NULL REFERENCES cursos_capacitacion(id_curso) ON DELETE RESTRICT,
  id_programa BIGINT REFERENCES programas_capacitacion(id_programa) ON DELETE SET NULL,
  fecha_asignacion DATE NOT NULL DEFAULT CURRENT_DATE,
  fecha_limite DATE NOT NULL,
  progreso INTEGER NOT NULL DEFAULT 0 CHECK (progreso BETWEEN 0 AND 100),
  estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente'
    CHECK (estado IN ('Pendiente', 'En progreso', 'Completado', 'Vencido')),
  resultado NUMERIC(5, 2) CHECK (resultado IS NULL OR resultado BETWEEN 0 AND 100),
  fecha_finalizacion DATE,
  observaciones TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (fecha_limite >= fecha_asignacion),
  CHECK (estado <> 'Completado' OR progreso = 100)
);

CREATE INDEX IF NOT EXISTS capacitaciones_empleados_empleado_idx
  ON capacitaciones_empleados (id_empleado);
CREATE INDEX IF NOT EXISTS capacitaciones_empleados_curso_idx
  ON capacitaciones_empleados (id_curso);
CREATE INDEX IF NOT EXISTS capacitaciones_empleados_estado_idx
  ON capacitaciones_empleados (estado);
CREATE INDEX IF NOT EXISTS capacitaciones_empleados_fecha_limite_idx
  ON capacitaciones_empleados (fecha_limite);
CREATE UNIQUE INDEX IF NOT EXISTS capacitaciones_empleados_abiertas_unique
  ON capacitaciones_empleados (id_empleado, id_curso)
  WHERE estado <> 'Completado';

CREATE OR REPLACE FUNCTION actualizar_updated_at_capacitacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS cursos_capacitacion_updated_at ON cursos_capacitacion;
CREATE TRIGGER cursos_capacitacion_updated_at
  BEFORE UPDATE ON cursos_capacitacion
  FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at_capacitacion();

DROP TRIGGER IF EXISTS programas_capacitacion_updated_at ON programas_capacitacion;
CREATE TRIGGER programas_capacitacion_updated_at
  BEFORE UPDATE ON programas_capacitacion
  FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at_capacitacion();

DROP TRIGGER IF EXISTS capacitaciones_empleados_updated_at ON capacitaciones_empleados;
CREATE TRIGGER capacitaciones_empleados_updated_at
  BEFORE UPDATE ON capacitaciones_empleados
  FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at_capacitacion();

ALTER TABLE cursos_capacitacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE programas_capacitacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE programa_cursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE capacitaciones_empleados ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  CREATE POLICY "training_courses_authenticated" ON cursos_capacitacion
    FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "training_programs_authenticated" ON programas_capacitacion
    FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "training_program_courses_authenticated" ON programa_cursos
    FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "training_assignments_authenticated" ON capacitaciones_empleados
    FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
