-- ShiftAI - Módulo 5: Evaluaciones de desempeño
-- Ejecutar en Supabase SQL Editor antes de usar la funcionalidad de evaluaciones.

CREATE TABLE IF NOT EXISTS public.evaluaciones_desempeno (
  id_evaluacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empleado BIGINT NOT NULL REFERENCES public.empleados(id_empleado) ON DELETE RESTRICT,
  titulo TEXT NOT NULL,
  periodo TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'Pendiente'
    CHECK (estado IN ('Pendiente', 'En progreso', 'Completado')),
  score_final INTEGER CHECK (score_final IS NULL OR (score_final BETWEEN 0 AND 100)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.detalles_evaluacion_360 (
  id_detalle BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_evaluacion BIGINT NOT NULL REFERENCES public.evaluaciones_desempeno(id_evaluacion) ON DELETE CASCADE,
  rol_evaluador TEXT NOT NULL
    CHECK (rol_evaluador IN ('Autoevaluación', 'Colega', 'Jefe Directo')),
  nombre_evaluador TEXT NOT NULL,
  score INTEGER CHECK (score IS NULL OR (score BETWEEN 0 AND 100)),
  comentarios TEXT,
  estado TEXT NOT NULL DEFAULT 'Pendiente'
    CHECK (estado IN ('Pendiente', 'Completado')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  submitted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_evaluaciones_desempeno_empleado
  ON public.evaluaciones_desempeno (id_empleado);

CREATE INDEX IF NOT EXISTS idx_evaluaciones_desempeno_estado
  ON public.evaluaciones_desempeno (estado);

CREATE INDEX IF NOT EXISTS idx_detalles_evaluacion_360_evaluacion
  ON public.detalles_evaluacion_360 (id_evaluacion);

CREATE INDEX IF NOT EXISTS idx_detalles_evaluacion_360_estado
  ON public.detalles_evaluacion_360 (estado);

ALTER TABLE public.evaluaciones_desempeno ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalles_evaluacion_360 ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  CREATE POLICY "evaluations_all_authenticated" ON public.evaluaciones_desempeno
    FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE POLICY "evaluation_details_all_authenticated" ON public.detalles_evaluacion_360
    FOR ALL TO authenticated USING (TRUE) WITH CHECK (TRUE);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
